package aoc2025.day07

import utils.BaseTest

class DaySevenTest extends BaseTest:

  private val input: Seq[String] = """.......S.......
                                    |...............
                                    |.......^.......
                                    |...............
                                    |......^.^......
                                    |...............
                                    |.....^.^.^.....
                                    |...............
                                    |....^.^...^....
                                    |...............
                                    |...^.^...^.^...
                                    |...............
                                    |..^...^.....^..
                                    |...............
                                    |.^.^.^.^.^...^.
                                    |...............
                                    |""".stripMargin.split("\n").toIndexedSeq

  "Parsed input in part one" must:

    "calculate the correct output" in:
      DaySeven.partOne(input) mustBe 21

  "Parsed input in part two" must:

    "calculate the correct output" in:
      DaySeven.partTwo(input) mustBe 40

end DaySevenTest
