package aoc2024.day08

import utils.BaseTest

class DayEightTest extends BaseTest:

  private val input: Seq[String] =
    """............
      |........0...
      |.....0......
      |.......0....
      |....0.......
      |......A.....
      |............
      |............
      |........A...
      |.........A..
      |............
      |............""".stripMargin.linesIterator.toSeq

  "Processing input for part one" must:

    "calculate the correct number of unique antinode locations" in:
      DayEight.partOne(input) mustBe 14

  "Processing input for part two" must:

    "calculate the correct number of unique antinode location while taking resonant harmonics into account" in:
      DayEight.partTwo(input) mustBe 34

end DayEightTest
